{
 "title": "Caddy",
 "description": "Prometheus + Loki + Promtail",
 "tags": [ "Caddy" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasourceloki", "label": "Datasource Loki", "query": "loki" },
   {
    "name": "logfile",
    "label": "Log file",
    "query": {}
   },
   { "name": "datasourceprometheus", "label": "Datasource Prometheus", "query": "prometheus" },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(up{job=~\"caddy.*\"},instance)"
    }
   },
   {
    "name": "handler",
    "label": "Handler",
    "query": {
     "query": "label_values({__name__=~\"^caddy.*\", handler=~\".*\"},handler)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of requests processed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "caddy_http_requests_total{instance=~\"$host\",handler=~\"$handler\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Status Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(caddy_http_request_duration_seconds_count{instance=~\"$host\",handler=~\"$handler\"}) by (code)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Middleware Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(caddy_http_request_errors_total{instance=~\"$host\",handler=~\"$handler\"}) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Request Duration (heatmap)",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(caddy_http_request_duration_seconds_bucket{instance=~\"$host\", handler=~\"$handler\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Rate of requests per second (avg 5m)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(caddy_http_requests_total{instance=~\"$host\",handler=~\"$handler\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Status",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(caddy_http_request_duration_seconds_count{instance=~\"$host\",handler=~\"$handler\"}) by (code)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(caddy_http_request_duration_seconds_count{instance=~\"$host\",handler=~\"$handler\"}[5m])) by (handler)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Countries",
   "type": "geomap",
   "gridPos": { "h": 17, "w": 18, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(geoip_country_name) (count_over_time({job=\"caddy\", geoip_country_name=~\".+\", filename=\"$logfile\"} [$__range]))"
    }
   ]
  },
  {
   "title": "Client IP",
   "type": "table",
   "gridPos": { "h": 17, "w": 6, "x": 18, "y": 13 },
   "targets": [
    {
     "expr": "{filename=\"$logfile\"} | json | line_format \"{{.status}}\""
    }
   ]
  },
  {
   "title": "HTTP(S) requests total",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(caddy_http_requests_total{instance=~\"$host\",handler=~\"$handler\"}[5m])*10) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Median response duration in seconds",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(caddy_http_response_duration_seconds_bucket[5m])))"
    }
   ]
  },
  {
   "title": "Requests In Flight",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(caddy_http_requests_in_flight{instance=~\"$host\",handler=~\"$handler\"}[1m])) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Middleware Errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(caddy_http_request_errors_total{instance=~\"$host\",handler=~\"$handler\"}[5m])*10) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Median response size in bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(caddy_http_response_size_bytes_bucket{instance=~\"$host\"}[5m])))"
    }
   ]
  },
  {
   "title": "Request/Response duration seconds",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(caddy_http_request_duration_seconds_count{instance=~\"$host\",handler=~\"$handler\"}[5m])) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "HTTP Status Errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(code) (caddy_http_request_duration_seconds_count{instance=~\"$host\", handler=~\"$handler\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Rag logs in table",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "{filename=\"$logfile\"} | json | line_format \"{{.status}}\""
    }
   ]
  },
  {
   "title": "Raw logs",
   "type": "logs",
   "gridPos": { "h": 33, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "{filename=\"$logfile\"} | json | line_format \"- [HTTP Status: {{.status}} - Duration: {{.duration}} - Client IP: {{.request_client_ip}} - Request: {{.request_uri}}]\""
    }
   ]
  }
 ]
}