{
 "title": "WireGuard Dashboard",
 "tags": [
  "wireguard",
  "networking"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Last Handshake",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by(allowed_ips) (time() - wireguard_latest_handshake_seconds{interface=~\".*\"})",
     "legendFormat": "{{allowed_ips}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(allowed_ips) (wireguard_sent_bytes_total{interface=~\".*\"} + wireguard_received_bytes_total{interface=~\".*\"})",
     "legendFormat": "{{allowed_ips}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by(allowed_ips) (rate(wireguard_sent_bytes_total{interface=~\".*\"}[5m]) * 8)",
     "legendFormat": "{{allowed_ips}} (Sent)"
    },
    {
     "expr": "sum by(allowed_ips) (rate(wireguard_received_bytes_total{interface=~\".*\"}[5m]) * 8)",
     "legendFormat": "{{allowed_ips}} (Received)"
    }
   ]
  }
 ]
}